Improvement - icon page main template
scania/corporate-ui-site pull request #97
Opened 2020-09-23 09:00 UTC by helloimela

**Describe pull-request**  
Update icon page templae

**Solving issue**  
Part of
Fixes: #92 

**How to test**  
1. Setup local strapi on this branch: https://github.com/scania/corporate-ui-cms/pull/16
2. Update database
3. Run corporate-ui-site with localhost (fetchData.js is pointing to localhost for now)
4. Check Icon Page following basic layout from Design
5. Check all pages is working with the new setup

**Screenshots**  
Current view in Icon Page
![image](https://user-images.githubusercontent.com/1199101/93990837-e60b4080-fd8b-11ea-9bcf-4552d1746426.png)

**Additional context**  
In XD, it has line above icon-list, will be added in another PR as part of Icon List task.

2020-09-23 10:15 UTC, helloimela commented
Note: Before merge, I need to change back fetchData pointing to fetch from SDDS instead

2020-09-25 11:19 UTC, mmexvr requested changes
![image](https://user-images.githubusercontent.com/35451568/94261158-b138ee00-ff31-11ea-86a6-3a5d683badf4.png)
Color of the icon is incorrect

Might have been fixed another branch?

2020-09-25 11:23 UTC, helloimela commented
> ![image](https://user-images.githubusercontent.com/35451568/94261158-b138ee00-ff31-11ea-86a6-3a5d683badf4.png)
> Color of the icon is incorrect
> 
> Might have been fixed another branch?

The color in the design is #161743 but we don't have it in our theme, so I make it the same with other icons (Scania blue). Since we will get a revamp on colour & foundation, should we keep it like this for now?

2020-09-25 12:41 UTC, mmexvr commented on src/app/components/icon-list/icon-list.component.ts
> +    this.icons.shift();
Can be removed

2020-09-25 12:48 UTC, helloimela commented on src/app/components/icon-list/icon-list.component.ts
> +    this.icons.shift();
This PR is still uses data from iconList component in cms, so it still need to parse a block of list separated with \n.

2020-09-28 10:55 UTC, mmexvr approved these changes

2020-09-29 12:17 UTC, merged